apiVersion: v2
name: strix
description: A Helm chart for deploying Strix AI Security Testing Agent on Kubernetes
type: application
version: 0.2.0
appVersion: "latest"
kubeVersion: ">=1.19.0-0"
keywords:
  - security
  - penetration-testing
  - ai
  - vulnerability-scanner
home: https://usestrix.com
icon: https://usestrix.com/favicon.ico
sources:
  - https://github.com/usestrix/strix
maintainers:
  - name: Strix Team
    email: hello@usestrix.com
annotations:
  artifacthub.io/prerelease: "false"
  artifacthub.io/license: Apache-2.0
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/category: security
  artifacthub.io/links: |
    - name: homepage
      url: https://usestrix.com
    - name: source
      url: https://github.com/usestrix/strix
  artifacthub.io/images: |
    - name: strix
      image: docker.io/usestrix/strix:latest
    - name: sandbox
      image: docker.io/usestrix/strix-sandbox:latest
    - name: dind
      image: docker:24-dind